# Generated by nixos-infect at runtime. Do not edit.
{ lib, ... }: {
  networking = {
    nameservers = [ "8.8.8.8" ];
    defaultGateway = "172.31.1.1";
    defaultGateway6 = {
      address = "fe80::1";
      interface = "eth0";
    };
    dhcpcd.enable = false;
    usePredictableInterfaceNames = lib.mkForce false;
    interfaces = {
      eth0 = {
        ipv4.addresses = [
          { address = "46.225.161.186"; prefixLength = 32; }
        ];
        ipv6.addresses = [
          { address = "2a01:4f8:1c19:fdad::1"; prefixLength = 64; }
          { address = "fe80::9000:7ff:fe39:3cb0"; prefixLength = 64; }
        ];
        ipv4.routes = [ { address = "172.31.1.1"; prefixLength = 32; } ];
        ipv6.routes = [ { address = "fe80::1"; prefixLength = 128; } ];
      };
    };
  };
  services.udev.extraRules = ''
    ATTR{address}=="92:00:07:39:3c:b0", NAME="eth0"
  '';
}
